# version format
version: "{build}"

# Operating system (build VM template)
os: Windows Server 2012 R2

environment:
    nodejs_version: "6.11.3"

# to run your custom scripts instead of automatic MSBuild
build_script:
  - npm install
  - npm install -g gulp
  - gulp browserify
  - gulp lint
  - npm test

# to disable automatic tests
test: off

# to disable deployment
deploy: off
